In [1]:
import numpy as np
import pandas as pd

In [ ]:
# Series -> 1D
# DataFrame -> 2D
# Kolom DataFrame -> kumpulan Series
# Pada ML -> kolom = fitur, baris = sample 
# Data kosong wajib dibersihkan karena ML sangat benci

In [43]:
# Series -> dimensi untuk menampung object dengan index
# Series -> 2 komponen utama (data dan index)
# membuat series dari list index otomatis
data_list = [10, 20, 30, 40, 50]
series1 = pd.Series(data_list)
series1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [45]:
# membuat series dari kustom index
hargaBuah = [15000, 25000, 30000]
namaBuah = ["apel", "jeruk", "mangga"]
series2 = pd.Series(data=hargaBuah, index=namaBuah)
series2

apel      15000
jeruk     25000
mangga    30000
dtype: int64

In [51]:
# membuat series dari dictionary
dataDict = {
    "Jakarta" : 20,
    "Bandung" : 30,
    "Semarang" : 43
}
series3 = pd.Series(dataDict)
series3

Jakarta     20
Bandung     30
Semarang    43
dtype: int64

In [47]:
# membuat series dengan data kosong
data_kosong = [1, 2, 3, np.nan, 4]
series4 = pd.Series(data_kosong) # Otomatis tipe data menjadi float ketika ada NaN
series4

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
dtype: float64

In [48]:
# DataFrame -> struktur data berbentuk 2 dimensi
# DataFrame -> ada 3 komponen utama (data, index, column)
# membuat dataframe dari dictionary list
dataPeserta = {
    "Nama" : ["Ganza", "Budi", "Tatang"],
    "Nilai" : [97, 77, 89],
    "Kota" : ["Surakarta", "Bali", "Kudus"]
}
df_peserta = pd.DataFrame(dataPeserta)
df_peserta

     Nama  Nilai       Kota
0   Ganza     97  Surakarta
1    Budi     77       Bali
2  Tatang     89      Kudus

In [49]:
# membuat dataframe dengan kustom index
id_peserta = ["L200231", "L12931" , "L023904"]
df_kustom = pd.DataFrame(data=dataPeserta, index=id_peserta)
df_kustom

           Nama  Nilai       Kota
L200231   Ganza     97  Surakarta
L12931     Budi     77       Bali
L023904  Tatang     89      Kudus

In [17]:
# Eksplorasi atribut Dataframe
print("1. Indeks Baris:", df_kustom.index) # Melihat index baris
print("\n2. Daftar Kolom:", df_kustom.columns) # Melihat nama kolom
print("\n3. Dimensi Data (Baris, Kolom):", df_kustom.shape) # Melihat dimensi
print("\n4. Tipe Data per Kolom:\n", df_kustom.dtypes) # Melihat tipe data setiap kolom
print("\n5. Konversi ke NumPy Array:\n", df_kustom.values) # Mengambil data mentah dalam bentuk numpy array

1. Indeks Baris: Index(['L200231', 'L12931', 'L023904'], dtype='str')

2. Daftar Kolom: Index(['Nama', 'Nilai', 'Kota'], dtype='str')

3. Dimensi Data (Baris, Kolom): (3, 3)

4. Tipe Data per Kolom:
 Nama       str
Nilai    int64
Kota       str
dtype: object

5. Konversi ke NumPy Array:
 [['Ganza' 97 'Surakarta']
 ['Budi' 77 'Bali']
 ['Tatang' 89 'Kudus']]

In [ ]:
# menambahkan nilai pada DataFrame
df_add_nilai = pd.DataFrame({
    "Angka" : [1, 2, 3, 4]
})

# Cara yang benar
# menimpa variabel (direkomendasikan)
df_add_nilai = df_add_nilai.add(10) # setiap itersasi ditambahkan 10 -> 1+10, 2+10, 3+10, 4+10
df_add_nilai

   Angka
0     11
1     12
2     13
3     14

In [42]:
# Seleksi fitur
data_medis = {
    "Tekanan Darah" : [120, 140, 130],
    "Koresterol" : [200, 210, 230],
    "Target Jantung" : [0, 1, 0] # 0 = sehat, 1 = sakit
}

# menambahkan ID medis
df_medis = pd.DataFrame(data_medis, index=["Pasien A", "Pasien B", "Pasien C"])

# memisahkan fitur X 
X = df_medis.drop(columns=["Target Jantung"])

# memisahkan target y 
y = df_medis["Target Jantung"]

X

          Tekanan Darah  Koresterol
Pasien A            120         200
Pasien B            140         210
Pasien C            130         230